version: '3'

services:
  client:
    environment:
      - WDS_SOCKET_PORT=0
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app

  api:
    container_name: api
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  nginx:
    container_name: nginx
    restart: always
    depends_on:
      - api
      - client
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
